---
- name: Backup show version and all other user level commands
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show ip interface brief
      register: print_output
    
    - debug: var=print_output.stdout_lines
    
    - name: save the output to a file(s)
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"
