---
- name: Privilage level commands
  hosts: all
  gather_facts: false
  connection: local
  
  tasks:
    - name: run enable mode/level commands
      ios_command:
        authorize: yes
        commands:
          - show run
      register: print_output
      
    - debug: var=print_output.stdout_lines
    
    - name: save that output fetched to sep files(s)
      copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"
