---
- name: Enable OSPF Playbook on a single router
  hosts: R1
  gather_facts: false
  connection: local
  
  tasks:
    - name: Enable ospf
      ios_config:
        provider: "{{ CLI }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
         
      register: print_output
      
    - debug: var=print_output
