---
- name: Enable OSPF Playbook on one device(router)
  hosts: R1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: girish
      password: cisco
  
  tasks:
    - name: Enable ospf
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0
         
      register: print_output
      
    - debug: var=print_output
